services:
  db:
    image: postgres:15-alpine
    container_name: raahi_db
    environment:
      POSTGRES_USER: raahi
      POSTGRES_PASSWORD: raahi_demo
      POSTGRES_DB: raahi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
